# Site settings
title: jmduke
email: me@jmduke.com
description: > # this means to ignore newlines until "baseurl:"
  I'm an engineer at Stripe.  I run Buttondown and Spoonbill.  I love Python, cocktails, poetry, and you.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jmduke.com" # the base hostname & protocol for your site
twitter_username: justinmduke
github_username:  jmduke

# Build settings
markdown: kramdown
